In [1]:
import nltk
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("swiggy_appReviews.csv")

In [3]:
df.head()

,Unnamed: 0,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,0,1bea42fe-2921-4fca-a184-803bbb3ed999,priyanka darole,https://play-lh.googleusercontent.com/a-/ALV-U...,Anything anything anywhere,5,0,4.50.1,2024-02-26 07:44:37,"Hey, thank you for your feedback. We request y...",2024-02-26 07:52:21,4.50.1
1,1,34d5884e-2eaa-4b90-9d77-feea3e578c41,Riya Yadav,https://play-lh.googleusercontent.com/a/ACg8oc...,Swiggy needs to be improved.. whenever I open ...,2,0,4.51.1,2024-02-26 07:42:55,"Hi, please let us know how we can make our ser...",2024-02-26 07:52:22,4.51.1
2,2,7e27618f-8c92-4220-9d99-eb0eb80b97f6,Dhilipraj Vasu,https://play-lh.googleusercontent.com/a/ACg8oc...,I enabled filter spam calls in Google phone di...,1,0,4.50.1,2024-02-26 07:42:44,"Hi, we are sorry about this. Please help us wi...",2024-02-26 07:52:22,4.50.1
3,3,ce1d0cb4-1ae0-4fde-8009-c2376711f3e6,vikash kumar,https://play-lh.googleusercontent.com/a/ACg8oc...,Worst app,1,0,NaN,2024-02-26 07:40:59,This shouldn't have happened. Kindly help us w...,2024-02-26 07:42:27,NaN
4,4,ff36287b-5d54-404e-8b54-48b0b374fa70,Santhiya Thevar,https://play-lh.googleusercontent.com/a-/ALV-U...,"Worst app ever , instamart order was placed , ...",1,0,4.50.1,2024-02-26 07:39:19,"Hello, we would like to know more about it. Pl...",2024-02-26 07:42:25,4.50.1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9552 entries, 0 to 9551
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            9552 non-null   int64
 1   reviewId              9552 non-null   object
 2   userName              9552 non-null   object
 3   userImage             9552 non-null   object
 4   content               9552 non-null   object
 5   score                 9552 non-null   int64
 6   thumbsUpCount         9552 non-null   int64
 7   reviewCreatedVersion  7280 non-null   object
 8   at                    9552 non-null   object
 9   replyContent          9536 non-null   object
 10  repliedAt             9536 non-null   object
 11  appVersion            7280 non-null   object
dtypes: int64(3), object(9)
memory usage: 895.6+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.shape

(9552, 12)

In [7]:
df1 = df[['content']]

In [8]:
df1 = df[['content']].copy()

### REMOVING NON TEXT VALUES

In [9]:
import re
def clean(text):
    text = re.sub('[^A-Za-z]+', ' ', text)
    return text

df1['Cleaned'] = df1['content'].apply(clean)
df1.head()

,content,Cleaned
0,Anything anything anywhere,Anything anything anywhere
1,Swiggy needs to be improved.. whenever I open ...,Swiggy needs to be improved whenever I open th...
2,I enabled filter spam calls in Google phone di...,I enabled filter spam calls in Google phone di...
3,Worst app,Worst app
4,"Worst app ever , instamart order was placed , ...",Worst app ever instamart order was placed they...

### NORMALIZATION

In [10]:
df1['Lowercase'] = df1['Cleaned'].apply(lambda x: " ".join(word.lower() for word in x.split()))
df1.head(2)

,content,Cleaned,Lowercase
0,Anything anything anywhere,Anything anything anywhere,anything anything anywhere
1,Swiggy needs to be improved.. whenever I open ...,Swiggy needs to be improved whenever I open th...,swiggy needs to be improved whenever i open th...

### REMOVING STOPWORDS

In [11]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saran\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [13]:
df1.head()

,content,Cleaned,Lowercase
0,Anything anything anywhere,Anything anything anywhere,anything anything anywhere
1,Swiggy needs to be improved.. whenever I open ...,Swiggy needs to be improved whenever I open th...,swiggy needs to be improved whenever i open th...
2,I enabled filter spam calls in Google phone di...,I enabled filter spam calls in Google phone di...,i enabled filter spam calls in google phone di...
3,Worst app,Worst app,worst app
4,"Worst app ever , instamart order was placed , ...",Worst app ever instamart order was placed they...,worst app ever instamart order was placed they...

In [14]:
df1['stopwords'] = df1['Lowercase'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))

In [15]:
df1.head(2)

,content,Cleaned,Lowercase,stopwords
0,Anything anything anywhere,Anything anything anywhere,anything anything anywhere,anything anything anywhere
1,Swiggy needs to be improved.. whenever I open ...,Swiggy needs to be improved whenever I open th...,swiggy needs to be improved whenever i open th...,swiggy needs improved whenever open app work i...

In [16]:
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from nltk import pos_tag
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\saran\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\saran\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\saran\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\saran\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

### PARTS OF SPEECH DICTIONARY

In [17]:
pos_dict = {'J': wordnet.ADJ, 'V': wordnet.VERB, 'N': wordnet.NOUN, 'R': wordnet.ADV}

def token_pos(text):
    return [
        (word, pos_dict.get(tag[0]))
        for word, tag in pos_tag(word_tokenize(text))
    ]

df1['POS tagged'] = df1['stopwords'].apply(token_pos)

In [18]:
df1.head(2)

,content,Cleaned,Lowercase,stopwords,POS tagged
0,Anything anything anywhere,Anything anything anywhere,anything anything anywhere,anything anything anywhere,"[(anything, n), (anything, n), (anywhere, r)]"
1,Swiggy needs to be improved.. whenever I open ...,Swiggy needs to be improved whenever I open th...,swiggy needs to be improved whenever i open th...,swiggy needs improved whenever open app work i...,"[(swiggy, a), (needs, v), (improved, v), (when..."

### LEMATATION

In [19]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

def lemmatize(pos_data):
    ans = " "
    for word, pos in pos_data:
        if not pos:
            lemma = word
        else:
            lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        ans = ans + " " + lemma
    return ans

df1['Lemma'] = df1['POS tagged'].apply(lemmatize)

In [20]:
df1.head(2)

,content,Cleaned,Lowercase,stopwords,POS tagged,Lemma
0,Anything anything anywhere,Anything anything anywhere,anything anything anywhere,anything anything anywhere,"[(anything, n), (anything, n), (anywhere, r)]",anything anything anywhere
1,Swiggy needs to be improved.. whenever I open ...,Swiggy needs to be improved whenever I open th...,swiggy needs to be improved whenever i open th...,swiggy needs improved whenever open app work i...,"[(swiggy, a), (needs, v), (improved, v), (when...",swiggy need improve whenever open app work i...

In [21]:
df["score"].value_counts()

score
1    5670
5    2783
4     479
2     322
3     298
Name: count, dtype: int64

In [22]:
def scores(RATES):
    if RATES > 3:  # Positive threshold
        return 0   # positive
    elif RATES < 3:  # Negative threshold
        return 1 # negative
    else:
        return 2 # neutral
df["scores"]=df["score"].apply(scores)

In [23]:
df.head(2)

,Unnamed: 0,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,scores
0,0,1bea42fe-2921-4fca-a184-803bbb3ed999,priyanka darole,https://play-lh.googleusercontent.com/a-/ALV-U...,Anything anything anywhere,5,0,4.50.1,2024-02-26 07:44:37,"Hey, thank you for your feedback. We request y...",2024-02-26 07:52:21,4.50.1,0
1,1,34d5884e-2eaa-4b90-9d77-feea3e578c41,Riya Yadav,https://play-lh.googleusercontent.com/a/ACg8oc...,Swiggy needs to be improved.. whenever I open ...,2,0,4.51.1,2024-02-26 07:42:55,"Hi, please let us know how we can make our ser...",2024-02-26 07:52:22,4.51.1,1

In [24]:
X=df1["Lemma"]
Y=df["scores"]

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [26]:
X_train.shape

(7641,)

# TF_IDF

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    stop_words='english',
    min_df=3,
    sublinear_tf=True
)

In [28]:
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec  = vectorizer.transform(X_test)

In [29]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_vec, Y_train)

MultinomialNB()

In [30]:
Y_pred = model.predict(X_test_vec)

In [32]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred))

0.8765044479330194

In [46]:
def predict_review(review):
    review_vec = vectorizer.transform([review])
    prediction = model.predict(review_vec)[0]

    label_map = {
        0: "positive",
        1: "negative",
        2: "positive"
    }
    return label_map[prediction]
print(predict_review("not liked"))

negative